### ISSUE TITLE
LG TV Webos notifications 

### ISSUE THREAD

**Issue by Bluelightcrew** [GameDevHobby/Domoticz-LGTV-WebOS-Plugin#13]
I found from a other home automation software a script to send notifications to the LG tv with webos.
Maybe you can include that in you scriot, that would be really cool
https://github.com/home-assistant/home-assistant/blob/master/homeassistant/components/notify/webostv.py

**Comment by Timmeehhh** [comment]
This shouldn't be too hard to achieve as both plugins run on pylgtv, the question is what would be the purpose of this?

**Comment by Bluelightcrew** [comment]
Display messages from domoticz on my TV while I watching TV!? The same exists for Kodi.

**Comment by odelma** [comment]
https://www.domoticz.com/forum/viewtopic.php?f=64&t=22337&p=192643

Did you try this?

**Comment by Bluelightcrew** [comment]
I'm the guy what is asking ;-) I will try it in my holiday, but I would nice to be intigrate it to LG Script

**Comment by GameDevHobby** [comment]
I added support for notifications, let me know what you think.

**Comment by RienduPre** [comment]
> I added support for notifications, let me know what you think.

How can I use these notifications ?
