### ISSUE TITLE
plug-in for webos 3.5

### ISSUE THREAD

**Issue by HEoHStyle** [GameDevHobby/Domoticz-LGTV-WebOS-Plugin#9]
Thanks for the plugin! but on webos 3.5 not all functions work, for example switching on the TV. Where can I see the button codes from my TV and fix them in the plugin?

**Comment by wmmudde** [comment]
Do you know How I have to install this plug-in?

**Comment by GameDevHobby** [comment]
You have to enable wake-on-lan on the tv from the settings for `on` to work.
